Repository NextDroid/potree, pull requests merged in 2020-08, with the labels that each got.

#185 Fix/issue182 extrinsics loading bug
  demo/calibrationManager.js
  demo/laneLoader.js
  demo/loaderHelper.js
  demo/rtkLoader.js
Labels: bug

#184 Close the Loop: annotating lanes in potree
  common/overlay.js
  common/playbar.js
  demo/loaderUtilities.js
  demo/paramLoader.js
Labels: enhancement

#186 Fix object detections loading bug
  demo/detectionLoader.js
Labels: bug

#190 Update Lambda to version 2
  common/playbar.js
Labels: enhancement

#200 AWS Lambda: UpdateLanes v3
  common/playbar.js
Labels: bug

#198 Fix control point loading errors and remove hard coded control point values
  demo/controlPointLoader.js
  demo/loaderHelper.js
  demo/loaderUtilities.js
Labels: bug, enhancement

#209 Fix Control Point Colors
  demo/controlPointLoader.js
Labels: bug

#210 Merge feature/issue197-update-calibration-panels-ui
  common/calibration-panels.css
  common/calibration-panels.js
  common/playbar.js
  demo/calibrationManager.js
  demo/loaderHelper.js
  demo/radar.html
Labels: enhancement

#212 Initial commit, fix bug with annotating lanes
  demo/laneLoader.js
Labels: bug

#213 Fix bug introduced with new AWS Lambda version
  common/playbar.js
Labels: bug

#214 Load multiple track files
  demo/loaderHelper.js
  demo/loaderUtilities.js
  demo/trackLoader.js
Labels: enhancement
